# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logininterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowLogIn(object):
    def setupUi(self, MainWindowLogIn):
        MainWindowLogIn.setObjectName("MainWindowLogIn")
        MainWindowLogIn.resize(250, 320)
        MainWindowLogIn.setMinimumSize(QtCore.QSize(250, 320))
        MainWindowLogIn.setMaximumSize(QtCore.QSize(250, 320))
        MainWindowLogIn.setStyleSheet("background-color: rgb(198, 196, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindowLogIn)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 40, 41, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/globe.svg"))
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.email_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.email_lineEdit.setGeometry(QtCore.QRect(60, 120, 130, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.email_lineEdit.setFont(font)
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 120, 28, 28))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/icons/icons/user.svg"))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.password_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.password_lineEdit.setGeometry(QtCore.QRect(60, 170, 130, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.password_lineEdit.setFont(font)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 170, 28, 28))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/icons/icons/unlock.svg"))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.signin_button = QtWidgets.QPushButton(self.centralwidget)
        self.signin_button.setGeometry(QtCore.QRect(60, 240, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.signin_button.setFont(font)
        self.signin_button.setObjectName("signin_button")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(130, 240, 61, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.invalidMsg_label = QtWidgets.QLabel(self.centralwidget)
        self.invalidMsg_label.setGeometry(QtCore.QRect(40, 210, 171, 20))
        self.invalidMsg_label.setStyleSheet("color: rgb(255, 0, 0);")
        self.invalidMsg_label.setAlignment(QtCore.Qt.AlignCenter)
        self.invalidMsg_label.setObjectName("invalidMsg_label")
        MainWindowLogIn.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowLogIn)
        QtCore.QMetaObject.connectSlotsByName(MainWindowLogIn)

    def retranslateUi(self, MainWindowLogIn):
        _translate = QtCore.QCoreApplication.translate
        MainWindowLogIn.setWindowTitle(_translate("MainWindowLogIn", "MainWindow"))
        self.signin_button.setText(_translate("MainWindowLogIn", "Sign in"))
        self.login_button.setText(_translate("MainWindowLogIn", "Log in"))
        self.invalidMsg_label.setText(_translate("MainWindowLogIn", "<html><head/><body><p><br/></p></body></html>"))
import resource_rc
